# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vbguest.auto_update = false
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.hostname = "node0"
  config.vm.network "private_network", ip: "192.168.100.11"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos_vagrant_TP2_II"
  end
end
