Vagrant.configure("2") do |config|
  config.vm.box = "B2TP2/centos7"
  
  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "192.168.1.11"
    node1.vm.hostname = "node1.tp2.b2"
    node1.vm.provision :shell, path: "./config1.sh"
  end
  
  config.vm.define "node2" do |node2|
    node2.vm.network "private_network", ip: "192.168.1.12"
    node2.vm.hostname = "node2.tp2.b2"
    node2.vm.provision :shell, path: "./config2.sh"
  end

end
