# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "B2TP2/centos7"

  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.2.21"
    node1.vm.provider "virtualbox" do |vb|
      vb.name = "b2.tp2.node1"
      vb.memory = "1024"
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.2.22"
    node2.vm.provider "virtualbox" do |vb|
      vb.name = "b2.tp2.node2"
      vb.memory = "512"
    end
  end

end
